### PR TITLE
fix(docgen): correctly extract default values (pending review)

### LINKED ISSUE #852: default value is parsed as string when it's a number
**Current behavior**

I have a prop:
```js
initialTabIndex: {
      type: [Number],
      default: 0,
    },
```
and I receive this parsed result from the simple loader:
```
defaultValue: {func: false, value: "0"} // "0" is a string
```

**Expected behavior**

expected this:
```
defaultValue: {func: false, value: 0} // 0 should be number
```

### PR DESCRIPTION
**Pull request by mesqueeb**
Fixes #852 

## Overview
I add an overview to see all the tests I added. Each time the "expected" result has its whitespaces and new lines stripped to check the expected result. This means: **these whitespaces and new lines are still there, but not being tested**.

image

> Please let me know if you don't agree with any of these expected results!!

## Questions

Two problems I ran into.

### 1. updated snaps

image

A bunch of snapshots were updated. These need to be reviewed if these changes are for the better or not. If not, last commit can be reverted.

### 2. broken VSCode Jest tester...?

While my tests all passed in the terminal, I had some trouble with the VSCode tests. They stayed grey:
  
Screenshot 2020-05-10 at 19 20 34

I'm not sure why, or if I should worry about it. :D

### 3. VSCode auto formatting

I don't know what part of my VSCode was different, but the eventual commits seem to have some weird spacing... Feel free to fix these by auto formatting again on your end!!

image

image

### CODE REVIEW

File: packages/vue-docgen-api/src/script-handlers/propHandler.ts [hunk 1]
```diff
@@ -16,6 +16,27 @@ import getTemplateExpressionAST from '../utils/getTemplateExpressionAST'
 
 type ValueLitteral = bt.StringLiteral | bt.BooleanLiteral | bt.NumericLiteral
 
+function getRawValueParsedFromFunctionsBlockStatementNode(
+	blockStatementNode: bt.BlockStatement
+): string {
+	const bodyNodeArray = blockStatementNode.body
+	const lastNode = bodyNodeArray.slice(-1)[0]
```
Comment (elevatebart) [inline packages/vue-docgen-api/src/script-handlers/propHandler.ts:23]: Why does the return statement have to be the last node?  
The following code is extracted from the `Button.vue` in basic example

```js
propComplexDefault: {
	type: Array,
	default: () => {
		if (typeof logger.mounted === 'function') {
			return []
		} else {
			return undefined
		}
	}
},
```

if you run `yarn start` or `yarn start basic` you will see the error.

Comment (elevatebart) [reply packages/vue-docgen-api/src/script-handlers/propHandler.ts]: Tell me what you think about my fix ;)

**Comment by mesqueeb** [comment]
@elevatebart LGTM! I can't merge though :) 
yoroshiku!!
