### PR TITLE
fix: load export const name = Vue.extends all good

### LINKED ISSUE #1069: Named export with Vue.extend does not extract props, slots, etc
**Current behavior**

When I use a TSX component with named export, the `vue-docgen-api` does not extract props, slots, etc. When I switch to default export, it works fine.

```tsx
// Works
export default Vue.extend({ // ... });
```

```tsx
// Does not work
export const Component = Vue.extend({ // ... });
```

**To reproduce**

In both cases please view devtools console and compare pass/fail objects.

- CodeSandbox: https://codesandbox.io/s/vigorous-moser-phvoc
- GitHub repository: https://github.com/kris-ellery/vue-docgen-api-bug

Screen Shot 2021-03-18 at 9 11 14 PM

I tried to figure out the issue, but couldn't pin-point the exact file or function. Possibly a related issue: https://github.com/vue-styleguidist/vue-styleguidist/issues/813

**Expected behavior**

Both default and named exports with `Vue.extend({});` should return complete `ComponentDoc` output.

### PR DESCRIPTION
**Pull request by elevatebart**
closes #1069

### CODE REVIEW

File: packages/vue-docgen-api/tests/components/tsx-named/named.tsx [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+			required: true,
+			type: String,
+			validator: (value: string) => ['red', 'green'].includes(value)
+		}
+	}, // props
+
+	render() {
+		return (
+			<span className={[`color-${this.color}`]}>
+				{/** @slot Default slot */}
```
Comment (kris-ellery) [inline packages/vue-docgen-api/tests/components/tsx-named/named.tsx:25]: @elevatebart heads up, I had a bug in my reproduction code. This is invalid syntax for slot comments in JSX, it should be:

```jsx
{
  /** @slot Default content */
  this.$slots.default
}
```
