### PR TITLE
fix(docgen):  fix ts array, intersection type print

### LINKED ISSUE #812: Incorrect array prop types when using vue-property-decorator
**Current behavior**
Vue-styleguidist uses TSArrayType instead of correct type.

**To reproduce**
https://github.com/Djaler/vue-styleguidist-vue-property-decorator-bug/commit/9d930c0c43ab78c7c415fb4ebd4de0bedcf6b521
Prop definition:
```
@Prop({type: Array, default: ()=>[]})
someArray!: string[];
```
In generated documentation type for this prop is `TSArrayType`

**Expected behavior**
In generated documentation type for this prop should be `string[]` or `Array<string>`

### PR DESCRIPTION
**Pull request by simsim0709**
This is my first pr in this project, so I may be wrong.

Please, let me know if I don't follow contribution guide.

Currently, `vue-docgen-api` doesn't support proper union and intersection type.

This pr tries to fixes both.

I think it fixes #812 as well.

before (current version):
Screen Shot 2020-04-14 at 4 08 14 PM

after (with this pr):
Screen Shot 2020-04-14 at 4 09 13 PM

### CODE REVIEW

**Comment by elevatebart** [comment]
Hello @simsim0709 

Your Pull request is great. 
- [x] It follows semantic commits
- [x] It documents what it does
- [x] the code is simple enough
- [x] It even fixes issue #812 (unless I am mistaken)

If you write one or two simple unit tests.
In your defense, I did not write the first unit tests for `getTypeAnnotation.ts` and I will do it right away. Once I am done, you can piggyback on those tests and add your own.
It will help the next maintainers understand what each function is supposed to do.

Thank you again

File: packages/vue-docgen-api/src/utils/getTypeFromAnnotation.ts [hunk 1]
```diff
@@ -25,18 +25,56 @@ const TS_TYPE_NAME_MAP: { [name: string]: string } = {
 	TSVoidKeyword: 'void',
 	TSUndefinedKeyword: 'undefined',
 	TSNullKeyword: 'null',
-	TSNeverKeyword: 'never'
+	TSNeverKeyword: 'never',
+	TSThisType: 'this'
```
Comment (elevatebart) [inline packages/vue-docgen-api/src/utils/getTypeFromAnnotation.ts:29]: What is `this` used for?

File: packages/vue-docgen-api/src/utils/getTypeFromAnnotation.ts [hunk 2]
```diff
@@ -25,18 +25,56 @@ const TS_TYPE_NAME_MAP: { [name: string]: string } = {
...
+}
+
+function printUnionOrIntersectionType(t: bt.TSType): string | number | boolean {
```
Comment (elevatebart) [inline packages/vue-docgen-api/src/utils/getTypeFromAnnotation.ts:32]: since this function is only used in the main function `getTypeObjectFromTSType` could you move it just before it?
I think it would make it easier to understand.

**Comment by elevatebart** [comment]
I added the needed test file here https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-docgen-api/src/utils/__tests__/getTypeFromAnnotation.ts

**Comment by elevatebart** [comment]
Thank you for the fixes

**Comment by simsim0709** [comment]
@elevatebart sorry, I haven't checked your comments.
Thank you for merging. 😄
